export const SECONDS_OF_MINUTE = 60

export const WORK_MINUTES_OF_CLOCK = 0.1

export const WORK_SECONDS_OF_CLOCK = WORK_MINUTES_OF_CLOCK * SECONDS_OF_MINUTE

export const BREAK_MINUTES_OF_CLOCK = 0.05

export const BREAK_SECONDS_OF_CLOCK = BREAK_MINUTES_OF_CLOCK * SECONDS_OF_MINUTE
